import json,pathlib
base=pathlib.Path(__file__).resolve().parent; root=base.parent
measures={x['file']:x for x in json.load(open(base/'measurements.json'))};prov=json.load(open(base/'provenance.json'))
def svg(name,w,h,body):
 f=base/(name+'.svg');f.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">{body}</svg>\n');return 'assets/'+f.name
def ring(x,y,r,c='#84ddd0'):
 return f'<circle cx="{x}" cy="{y}" r="{r}" fill="{c}" fill-opacity=".36" stroke="{c}" stroke-width="8"/>'
def line(d,c='#84ddd0',width=9):return f'<path d="{d}" fill="none" stroke="{c}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"/>'
ov={}
ov['intake-scan']=svg('intake-scan-overlay-v3',1536,1024,line('M470 355H1230 M470 510H1230 M470 665H1230 M470 820H1230',width=4))
ov['carrier-active']=svg('carrier-active-overlay-v3',1254,1254,ring(626,344,49)+ring(482,352,16)+ring(773,352,16))
ov['relay-connecting']=svg('relay-connecting-overlay-v3',1024,1536,line('M391 648H475',width=12)+ring(428,774,13))
ov['relay-linked']=svg('relay-linked-overlay-v3',1024,1536,line('M391 639L420 672L478 610',width=13)+ring(483,770,14))
ov['civic-linked']=svg('civic-linked-overlay-v3',1024,1536,line('M388 336L445 380L541 279',width=15)+ring(456,522,24))
ov['civic-public']=svg('civic-public-overlay-v3',1024,1536,line('M466 280V336 M466 336L395 386 M466 336L540 365',width=14)+''.join(ring(x,y,24) for x,y in [(456,522),(402,620),(507,611)]))
ov['controller-active']=svg('controller-active-overlay-v3',1254,1254,'<rect x="475" y="260" width="165" height="165" fill="none" stroke="#eaba74" stroke-width="18"/>')
ov['controller-disabled']=svg('controller-disabled-overlay-v3',1254,1254,line('M485 270L630 415 M630 270L485 415','#b9c3bf',18))
ov['signal-restored']=svg('signal-restored-overlay-v3',1024,1536,ring(463,591,58))
ov['marker']=svg('approach-marker-overlay-v3',1536,1024,line('M615 217H945 M880 160L950 217L880 270','#eed8a6',12))
for state,top in [('low',750),('high',620)]:
 body=f'<path d="M402 515H1130L1280 1024H290Z" fill="#63878d" fill-opacity=".44"/>'+''.join(line(f'M{390+i%3*15} {top+i*32}H{1150+i%3*20}','#b5d0cd',4) for i in range(8))
 ov['water-'+state]=svg('spillway-water-'+state+'-v3',1536,1024,body)
ov['dawn']=svg('dawn-atmosphere-v3',1536,1024,'<defs><linearGradient id="d" x2="0" y2="1"><stop stop-color="#e9b675" stop-opacity=".28"/><stop offset=".65" stop-color="#bfd1cf" stop-opacity=".05"/><stop offset="1" stop-color="#bfd1cf" stop-opacity="0"/></linearGradient></defs><path d="M0 0H1536V1024H0Z" fill="url(#d)"/>')
anchors={'env-l2-v3.png':[768,552],'env-l3-v3.png':[768,442],'env-l4-v3.png':[819,558],'env-l5-v3.png':[768,451],'carrier-rear-v3.png':[627,1133],'relay-node-v3.png':[512,1525],'civic-node-v3.png':[512,1515],'controller-v3.png':[625,1232],'spillway-closed-v3.png':[768,998],'spillway-open-v3.png':[768,998],'barrier-closed-v3.png':[768,852],'barrier-open-v3.png':[768,852]}
crops={'carrier-rear-v3.png':[30,90,1195,1050],'relay-node-v3.png':[185,0,655,1536],'civic-node-v3.png':[10,20,1005,1505],'controller-v3.png':[275,15,680,1225]}
assets=[]
for f,m in measures.items():
 a=dict(m);a.update(id=f.removesuffix('.png').upper(),file='assets/'+f,anchor={'xy':anchors[f],'space':'source pixels','kind':'vanishing point' if f.startswith('env-') else 'ground'},displayCrop=crops.get(f,[0,180,1536,680] if f.startswith('barrier-') else [0,0,m['width'],m['height']]),pivotNormalized=[anchors[f][0]/m['width'],anchors[f][1]/m['height']],layer='midground' if f.startswith('env-') else 'actor' if f.startswith('carrier-') else 'roadside',blend='source-over',rgbaDecodeBytes=m['width']*m['height']*4,approval='new revision3 candidate; user review pending',provenance={'method':'built-in image_gen; transparent_background true','source':prov[f],'processing':'copied unmodified'},collision='None in Phase2; later authored geometry, never alpha bounds');assets.append(a)
for key,f in ov.items():assets.append({'id':key.upper(),'file':f,'layer':'state-overlay','blend':'source-over','approval':'new revision3 candidate; user review pending','provenance':{'method':'code-native SVG effect; no replacement body'},'bytes':(root/f).stat().st_size,'alignment':'same full source canvas as body; share crop/scale/anchor, no independent transform'})
reuse={'delivery':'../revision-v2/assets/delivery-architecture-v2.png','signal':'../revision-v2/assets/signal-dead-v2.png','gate':'../revision-v2/assets/service-gate-open-v2.png','bus':'../assets/evac-bus-rear-v1.png','vlad':'../assets/vlad-neutral-v1.png','omega':'../assets/omega-symbol-v1.svg','skyline':'../../../../public/bastrop37/assets/environment/city-skyline-v4.png','road':'../../../../public/bastrop37/assets/environment/road-loop-v4.png','sedan':'../../../../public/bastrop37/assets/sprites/traffic-sedan.png','coupe':'../../../../public/bastrop37/assets/sprites/traffic-coupe.png','hauler':'../../../../public/bastrop37/assets/sprites/traffic-hauler.png','jo':'../../../../public/bastrop37/assets/sprites/bike-normal-straight.png'}
def state(body,*effects):return {'body':reuse.get(body,'assets/'+body+'.png'),'overlays':[ov[x] for x in effects]}
groups={
'ENV-L1':{'delivery':state('delivery')},'PROP-SIGNAL':{'dead':state('signal'),'restored-limited':state('signal','signal-restored')},'PROP-SERVICE-GATE':{'open':state('gate'),'approach-marker':state('gate','marker'),'blocked-crossing':state('barrier-closed-v3')},
'ENV-L2':{'freight-substation':state('env-l2-v3')},'PROP-INTAKE':{'neutral':state('gate'),'scan':state('gate','intake-scan')},'VEH-RECOVERY':{'neutral':state('carrier-rear-v3'),'active':state('carrier-rear-v3','carrier-active')},
'ENV-L3':{'market-relay':state('env-l3-v3')},'PROP-RELAY':{'dormant':state('relay-node-v3'),'connecting':state('relay-node-v3','relay-connecting'),'linked':state('relay-node-v3','relay-linked')},
'ENV-L4':{'reservoir-lower-road-civic-approach':state('env-l4-v3')},'PROP-SPILLWAY':{'closed':state('spillway-closed-v3'),'open':state('spillway-open-v3'),'water-low':state('spillway-open-v3','water-low'),'water-high':state('spillway-open-v3','water-high')},'PROP-ROADBLOCK':{'closed':state('barrier-closed-v3'),'open':state('barrier-open-v3'),'controller-active':state('controller-v3','controller-active'),'controller-disabled':state('controller-v3','controller-disabled')},'VEH-EVAC':{'neutral':state('bus')},'ENV-L5':{'civic-night':state('env-l5-v3'),'dawn-after-release':state('env-l5-v3','dawn')},'PROP-CIVIC-NODE':{'dormant':state('civic-node-v3'),'linked-local':state('civic-node-v3','civic-linked'),'public-active-final-only':state('civic-node-v3','civic-public')}}
for states in groups.values():
 for s in states.values():
  for f in [s['body']]+s['overlays']:assert (root/f).exists(),f
out={'version':3,'kind':'Phase2 isolated art register; not runtime','approval':'Delivery revision2 user approved 2026-09-27; all new revision3 bodies/effects pending full review','pathBase':'directory containing manifest','canonicalGroups':groups,'assets':assets,'reuse':reuse,'reuseApproval':{'delivery/signal/gate':'approved revision2 treatment','original road/rider/traffic/Vlad/Omega':'retained approved direction','bus':'v1 raster retained for material fit; this composed use pending review'},'stateRules':['Relay local readiness only; Omega remains contained.','Civic public-active and dawn only after final release.','Restored signal limited to epilogue, not Delivery.','Controller state distinct from barrier geometry.','Water remains lateral/background, never fluid simulation.'],'specialCrops':{'spillwayInnerGate':[402,360,728,540],'envL4GateBay':[[420,347],[551,514]],'envL4ApronNearEdge':[[1140,652],[1536,868]],'envL4PortalFloor':[[1230,610],[1403,648]],'busDisplayCrop':[165,90,920,1070],'busGround':[625,1160]},'limitations':['Static art states, not implemented mechanics.','Barrier fixed feet align but top lamp/upper housing differs by75source pixels; avoid automatic crossfade/tween of whole sprite.','L4 inner-gate crop must be fitted to the bay; full extra frame causes double framing.','Camera actual measured vanishing anchors supersede prompt targets.','Memory excludes browser/GPU copies and mipmaps.']}
(root/'asset-manifest.json').write_text(json.dumps(out,indent=2)+'\n');print('14 groups',len(assets),'asset entries',sum(len(x) for x in groups.values()),'explicit states')
